
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS courses;
CREATE TABLE student (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32));
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category_name VARCHAR (150));
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category_id INTEGER NOT NULL,
 name VARCHAR (150),
FOREIGN KEY(category_id) REFERENCES categories(id));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;